# https://github.com/ls-lint/docs

ls:
  # keep-sorted start
  .bash: snake_case
  .json: kebab-case
  .sh: snake_case
  .toml: kebab-case
  .yaml: kebab-case
  .yml: kebab-case
  .zsh: snake_case
  # keep-sorted end

ignore:
  # keep-sorted start
  - .git
  - vendor
  # keep-sorted end
