# keep-sorted start
- id: just-format
  name: Format Justfiles with just --fmt
  entry: scripts/just-fmt.sh
  language: script
  files: '\.?[jJ]ustfile$'
- id: pint
  name: Validate Prometheus rules with pint
  entry: pint --offline lint
  language: golang
  additional_dependencies:
    - github.com/cloudflare/pint/cmd/pint@v0.73.7
  types:
    - yaml
# keep-sorted end
