# keep-sorted start
- id: check-json-schema
  name: Check JSON schema
  entry: check-json-schema.py
  language: python
  types:
    - json
- id: format-justfile
  name: Format Justfiles
  entry: scripts/just-fmt.sh
  language: script
  files: '\.?[jJ]ustfile$'
- id: pint
  name: Validate Prometheus rules with pint
  entry: pint --offline lint
  language: golang
  additional_dependencies:
    - github.com/cloudflare/pint/cmd/pint@v0.73.7
  types:
    - yaml
# keep-sorted end
