# keep-sorted start newline_separated=yes
- id: check-yamlschema-local
  name: Ensure JSON schemas of YAML files are local
  description: Prevent YAML files from using remote schema references
  language: pygrep
  entry: '# yaml-language-server: \$schema=http'
  types:
    - yaml

- id: forbid-colon-filenames
  name: Forbid colons in filenames
  description: "Error: filenames containing ':' are not allowed."
  entry: "Filenames must not contain a colon (:) in their name."
  language: fail
  files: ".*:.*"  # match any path containing a colon

- id: just-format
  alias: format-justfiles
  name: Format Justfiles
  entry: scripts/just-fmt.sh
  language: script
  files: '\.?[jJ]ustfile$'

- id: pint
  name: Validate Prometheus rules with pint
  entry: pint --offline lint
  language: golang
  additional_dependencies:
    - github.com/cloudflare/pint/cmd/pint@v0.73.7
  types:
    - yaml
# keep-sorted end
