# keep-sorted start
- id: check-jsonschema
  name: Check JSON schema
  language: script
  entry: scripts/check-jsonschema.sh
  types:
    - json
- id: format-justfile
  name: Format Justfiles
  language: script
  entry: scripts/just-fmt.sh
  files: '\.?[jJ]ustfile$'
- id: pint
  name: Validate Prometheus rules with pint
  language: golang
  additional_dependencies:
    - github.com/cloudflare/pint/cmd/pint@v0.73.7
  entry: pint --offline lint
  types:
    - yaml
# keep-sorted end
