- id: format-justfile
  name: Format Justfiles
  language: script
  entry: scripts/pre-commit-just.sh
  files: '\.?[jJ]ustfile$'
- id: pint
  name: Validate Prometheus rules with pint
  language: golang
  additional_dependencies:
    - github.com/cloudflare/pint/cmd/pint@v0.73.7
  entry: pint --offline lint
  types:
    - yaml
