# keep-sorted start newline_separated=yes
- id: check-bash-shebang
  name: Check bash scripts use portable shebang
  description: Ensure bash scripts use '#!/usr/bin/env bash' instead of '#!/bin/bash'
  language: script
  entry: scripts/check-bash-shebang.sh
  types:
    - bash

- id: check-yaml-language-server
  name: Check YAML files have yaml-language-server directive
  description: Check that YAML files include a yaml-language-server schema directive
  language: script
  entry: scripts/check-yaml-language-server.sh
  types:
    - yaml

- id: check-yamlschema-local
  name: Check JSON schemas of YAML files are local
  description: Prevent YAML files from using remote schema references
  language: pygrep
  entry: '# yaml-language-server: \$schema=http'
  types:
    - yaml

- id: forbid-colon-filenames
  name: Forbid colons in filenames
  description: "Error: filenames containing ':' are not allowed."
  entry: "Filenames must not contain a colon (:) in their name."
  language: fail
  files: ".*:.*"  # match any path containing a colon

- id: if-this-then-that
  alias: ifttt
  name: If This Then That
  description: Ensure file changes are accompanied by other file changes.
  language: python
  entry: if_this_then_that.py

- id: just-format
  alias: format-justfiles
  name: Format Justfiles
  entry: scripts/just-fmt.sh
  language: script
  files: '\.?[jJ]ustfile$'

- id: pint
  name: Validate Prometheus rules with pint
  entry: pint --offline lint
  language: golang
  additional_dependencies:
    - github.com/cloudflare/pint/cmd/pint@v0.73.7
  types:
    - yaml
# keep-sorted end
