[project]
name = "pre-commit-check-jsonschema"
version = "0.1.0"
dependencies = ["check-jsonschema"]
requires-python = ">=3.8"

[project.scripts]
check-json-schema = "scripts.check_json_schema:main"

[tool.setuptools]
packages = ["scripts"]

[tool.setuptools.package-dir]
"" = "."
